export const AFFILIATE_LINKS = [
  { name: "Booking.com", url: "https://booking.tpx.gr/pO1xgUOk" },
  { name: "Trip.com", url: "https://trip.tpx.gr/xuZyhawM" },
  { name: "GetYourGuide", url: "https://getyourguide.tpx.gr/N4hqBYBh" },
  { name: "Discover Cars", url: "https://discovercars.tpx.gr/Db7PkpPH" },
  { name: "Klook", url: "https://klook.tpx.gr/maKAx6cu" },
  { name: "Tiqets", url: "https://tiqets.tpx.gr/4XvdA3sA" },
  { name: "Omio", url: "https://omio.tpx.gr/HhKpT0j2" },
  { name: "Hotels.com", url: "https://hotels.tpx.gr/HZcgZ2jB" },
  { name: "Sea Radar", url: "https://searadar.tpx.gr/PdA1Y1ul" },
  { name: "Go City", url: "https://gocity.tpx.gr/mvQ9kUHY" },
  { name: "FlixBus", url: "https://tpx.gr/nd8xOURD" },
  { name: "Expedia", url: "https://expedia.tpx.gr/oZmiqQ00" },
  { name: "Aviasales", url: "https://aviasales.tpx.gr/EDLTCi50" },
];

// هذا السطر يحل مشكلة LandingView.tsx
export const PARTNERS = AFFILIATE_LINKS;

export const SERVICES = {
  flight: {
    id: "flight",
    titleKey: "cheap_flights",
    icon: "Plane",
    greetings: {
      en: "Hi! I'm Fastamor. Tell me your origin, destination and travel dates. I'll find the best flights instantly!",
      ar: "مرحبا! أنا Fastamor. أخبرني بمدينة الانطلاق والوجهة وتاريخ السفر. سأجد لك أفضل الرحلات فورا!",
      fr: "Bonjour! Je suis Fastamor. Dites-moi votre origine, destination et dates. je trouverai les meilleurs vols!",
      es: "¡Hola! Soy Fastamor. Dime tu origen, destino y fechas. ¡encontraré los mejores vuelos al instante!"
    }
  },
  hotel: {
    id: "hotel",
    titleKey: "top_hotels",
    icon: "Building2",
    greetings: {
      en: "Hi! I'm Fastamor. Tell me your destination and dates. I'll find top hotels for you!",
      ar: "مرحبا! أنا Fastamor. أخبرني بوجهتك والتواريخ. سأجد لك أفضل الفنادق!",
      fr: "Bonjour! Je suis Fastamor. Dites-moi votre destination et vos dates. je trouverai les meilleurs hôtels!",
      es: "¡Hola! Soy Fastamor. Dime tu destino y fechas. ¡encontraré los mejores hoteles!"
    }
  },
  taxi: {
    id: "taxi",
    titleKey: "car_rental",
    icon: "Car",
    greetings: {
      en: "Hi! I'm Fastamor. Tell me pickup and destination. I'll find the best transfer for you!",
      ar: "مرحبا! أنا Fastamor. أخبرني بنقطة الانطلاق والوجهة. سأجد أفضل وسيلة نقل!",
      fr: "Bonjour! Je suis Fastamor. Donnez-me votre point de départ et destination. je trouverai le meilleur transfert!",
      es: "¡Hola! Soy Fastamor. Dime el punto de recogida y destino. ¡encontraré el mejor traslado!"
    }
  },
  experience: {
    id: "experience",
    titleKey: "experiences",
    icon: "Ticket",
    greetings: {
      en: "Hi! I'm Fastamor. Tell me which city. I'll find amazing tours and experiences!",
      ar: "مرحبا! أنا Fastamor. أخبرني بالمدينة. سأجد لك أروع الجولات والتجارب!",
      fr: "Bonjour! Je suis Fastamor. Dites-moi la ville. je trouverai les meilleures expériences!",
      es: "¡Hola! Soy Fastamor. Dime la ciudad. ¡encontraré los mejores tours y experiencias!"
    }
  },
  bus: {
    id: "bus",
    titleKey: "trains_buses",
    icon: "Bus",
    greetings: {
      en: "Hi! I'm Fastamor. Tell me your route and date. I'll find the cheapest bus tickets!",
      ar: "مرحبا! أنا Fastamor. أخبرني بمسارك وتاريخ السفر. سأجد أرخص تذاكر الحافلات!",
      fr: "Bonjour! Je suis Fastamor. Dites-moi votre trajet et date. je trouverai les bus les moins chers!",
      es: "¡Hola! Soy Fastamor. Dime tu ruta y fecha. ¡encontraré los autobuses más baratos!"
    }
  }
};

export const I18N = {
  en: {
    home: "Home",
    discover: "Discover",
    join: "Start Planning",
    services: "Book Services",
    flash_sale: "🚀 FLASH SALE: UP TO 50% OFF FLIGHTS & HOTELS — CLICK HERE",
    hero_badge: "✨ Your Personal AI Concierge",
    hero_title: "Travel With",
    hero_desc: "Skip the endless searching. Tell our AI where you want to go, and instantly get the best prices on flights, hotels, and tours across 200+ providers.",
    hero_btn_start: "Start Exploring",
    hero_btn_how: "See how it works",
    cheap_flights: "Flights",
    top_hotels: "Hotels",
    experiences: "Tours",
    cruises: "Cruises",
    car_rental: "Transfers",
    trains_buses: "Trains & Buses",
    luxury_resorts: "Luxury Resorts",
    book_everything: "Book Everything.",
    itinerary_desc: "Your entire itinerary handled in one smart interface.",
    how_it_works: "How It Works",
    step1_title: "Tell Fastamor",
    step1_desc: "Just type or speak naturally. 'Find me a cheap flight to Paris next Friday.'",
    step2_title: "AI Searches",
    step2_desc: "In seconds, we scan 200+ providers across the web to find the hidden gems.",
    step3_title: "Book Direct",
    step3_desc: "Click the links to book directly with the provider. Zero hidden fees from us.",
    placeholder: "Ask anything about your trip...",
    search_flights: "Search Flights",
    search_hotels: "Search Hotels",
    search_transfers: "Search Transfers",
    send: "Send",
    listening: "Listening...",
    searching: "Searching...",
    results_for: "Results for your request",
    explore: "Explore Activities",
    deals: "Hot Deals",
    book_now: "Book Now",
    trending: "Trending This Hour",
    results: "Results will appear here...",
    top_picks: "Top Picks for You",
    direct_links: "Direct Booking Links",
    best_match: "Best Match",
    view_details: "View Details",
    price: "Price",
    about_us: "About Us",
    contact_us: "Contact Us",
    privacy: "Privacy Policy",
    terms: "Terms & Conditions",
    language: "Language",
    currency: "Currency",
    rights: "All rights reserved.",
    powered_by: "Powered by Travelpayouts",
    admin_password_prompt: "Enter Admin Password:",
    unauthorized: "Unauthorized Access"
  },
  ar: {
    home: "الرئيسية",
    discover: "اكتشف",
    join: "ابدأ التخطيط",
    services: "خدمات الحجز",
    flash_sale: "🚀 عرض حصري: خصم يصل إلى 50% على الرحلات والفنادق — اضغط هنا",
    hero_badge: "✨ مساعدك الشخصي بالذكاء الاصطناعي",
    hero_title: "سافر مع",
    hero_desc: "توقف عن البحث الطويل. أخبر مساعدنا الذكي أين تريد الذهاب وستحصل فورا على أفضل الأسعار للرحلات والفنادق والجولات عبر 200+ مزود خدمة.",
    hero_btn_start: "ابدأ الاستكشاف",
    hero_btn_how: "شاهد كيف يعمل",
    cheap_flights: "طيران",
    top_hotels: "فنادق",
    experiences: "جولات",
    cruises: "كروز",
    car_rental: "توصيلات",
    trains_buses: "قطارات وحافلات",
    luxury_resorts: "منتجعات فاخرة",
    book_everything: "احجز كل شيء.",
    itinerary_desc: "خطط لرحلتك بالكامل من خلال واجهة واحدة ذكية.",
    how_it_works: "كيف يعمل؟",
    step1_title: "تحدث مع فاستامور",
    step1_desc: "اكتب أو تحدث بشكل طبيعي. 'ابحث لي عن رحلة رخيصة إلى باريس الجمعة القادمة'.",
    step2_title: "البحث الذكي",
    step2_desc: "في ثوانٍ، نقوم بمسح 200+ مزود خدمة عبر الويب للعثور على أفضل العروض.",
    step3_title: "احجز مباشرة",
    step3_desc: "اضغط على الروابط للحجز مباشرة مع المزود. لا توجد رسوم خفية منا.",
    placeholder: "اسأل عن أي شيء يخص رحلتك...",
    search_flights: "البحث عن رحلات",
    search_hotels: "البحث عن فنادق",
    search_transfers: "البحث عن نقل",
    send: "إرسال",
    listening: "جاري الاستماع...",
    searching: "جاري البحث...",
    results_for: "نتائج طلبك",
    explore: "استكشف الأنشطة",
    deals: "عروض مميزة",
    book_now: "احجز الآن",
    trending: "شائع هذه الساعة",
    results: "ستظهر النتائج هنا...",
    top_picks: "أفضل التوصيات لك",
    direct_links: "روابط الحجز المباشرة",
    best_match: "أفضل تطابق",
    view_details: "عرض التفاصيل",
    price: "السعر",
    about_us: "من نحن",
    contact_us: "اتصل بنا",
    privacy: "سياسة الخصوصية",
    terms: "الشروط والأحكام",
    language: "اللغة",
    currency: "العملة",
    rights: "جميع الحقوق محفوظة.",
    powered_by: "بدعم من Travelpayouts",
    admin_password_prompt: "أدخل كلمة مرور المسؤول:",
    unauthorized: "دخول غير مصرح به"
  },
  fr: {
    home: "Accueil",
    discover: "Découvrir",
    join: "Commencer",
    services: "Services",
    flash_sale: "🚀 VENTE FLASH : JUSQU'À 50% DE RÉDUCTION — CLIQUEZ ICI",
    hero_badge: "✨ Votre Concierge IA Personnel",
    hero_title: "Voyagez avec",
    hero_desc: "Arrêtez de chercher sans fin. Dites à notre IA où vous voulez aller, et obtenez instantanément les meilleurs prix sur les vols, hôtels et circuits sur 200+ fournisseurs.",
    hero_btn_start: "Commencer",
    hero_btn_how: "Comment ça marche",
    cheap_flights: "Vols",
    top_hotels: "Hôtels",
    experiences: "Tours",
    cruises: "Croisières",
    car_rental: "Transferts",
    trains_buses: "Trains & Bus",
    luxury_resorts: "Resorts de Luxe",
    book_everything: "Réservez Tout.",
    itinerary_desc: "Tout votre itinéraire géré dans une seule interface intelligente.",
    how_it_works: "Comment ça marche",
    step1_title: "Dites à Fastamor",
    step1_desc: "Écrivez ou parlez naturellement. 'Trouve-moi un vol pas cher pour Paris vendredi prochain.'",
    step2_title: "L'IA Recherche",
    step2_desc: "En quelques secondes, nous scannons 200+ fournisseurs pour trouver les perles rares.",
    step3_title: "Réservez Direct",
    step3_desc: "Cliquez sur les liens pour réserver directement. Zéro frais cachés chez nous.",
    placeholder: "Demandez n'importe quoi...",
    search_flights: "Rechercher Vols",
    search_hotels: "Rechercher Hôtels",
    search_transfers: "Rechercher Transferts",
    send: "Envoyer",
    listening: "Écoute...",
    searching: "Recherche...",
    results_for: "Résultats pour votre demande",
    explore: "Explorer",
    deals: "Bons Plans",
    book_now: "Réserver",
    trending: "Tendance",
    results: "Les résultats apparaîtront ici...",
    top_picks: "Nos Meilleurs Choix",
    direct_links: "Liens de Réservation",
    best_match: "Meilleur Choix",
    view_details: "Voir Détails",
    price: "Prix",
    about_us: "À Propos",
    contact_us: "Contactez-nous",
    privacy: "Confidentialité",
    terms: "Conditions",
    language: "Langue",
    currency: "Devise",
    rights: "Tous droits réservés.",
    powered_by: "Propulsé par Travelpayouts",
    admin_password_prompt: "Entrez le mot de passe administrateur :",
    unauthorized: "Accès non autorisé"
  },
  es: {
    home: "Inicio",
    discover: "Descubrir",
    join: "Empezar",
    services: "Servicios",
    flash_sale: "🚀 VENTA FLASH: HASTA 50% DE DESCUENTO — CLIC AQUÍ",
    hero_badge: "✨ Tu Conserje IA Personal",
    hero_title: "Viaja con",
    hero_desc: "Deja de buscar sin fin. Dile a nuestra IA a dónde quieres ir, y obtén al instante los mejores precios en vuelos, hoteles y tours en más de 200 proveedores.",
    hero_btn_start: "Explorar",
    hero_btn_how: "Cómo funciona",
    cheap_flights: "Vuelos",
    top_hotels: "Hoteles",
    experiences: "Tours",
    cruises: "Cruceros",
    car_rental: "Traslados",
    trains_buses: "Trenes & Buses",
    luxury_resorts: "Resorts de Lujo",
    book_everything: "Reserva Todo.",
    itinerary_desc: "Todo tu itinerario gestionado en una interfaz inteligente.",
    how_it_works: "Cómo Funciona",
    step1_title: "Dile a Fastamor",
    step1_desc: "Escribe o habla naturalmente. 'Búscame un vuelo barato a París el próximo viernes'.",
    step2_title: "IA Busca",
    step2_desc: "En segundos, escaneamos más de 200 proveedores para encontrar las mejores ofertas.",
    step3_title: "Reserva Directo",
    step3_desc: "Haz clic en los enlaces para reservar directamente. Sin cargos ocultos por nuestra parte.",
    placeholder: "Pregunta cualquier cosa...",
    search_flights: "Buscar Vuelos",
    search_hotels: "Buscar Hoteles",
    search_transfers: "Buscar Traslados",
    send: "Enviar",
    listening: "Escuchando...",
    searching: "Buscando...",
    results_for: "Resultados para tu solicitud",
    explore: "Explorar",
    deals: "Ofertas",
    book_now: "Reservar",
    trending: "Tendencias",
    results: "Los resultados aparecerán aquí...",
    top_picks: "Mejores Opciones",
    direct_links: "Enlaces Directos",
    best_match: "Mejor Opción",
    view_details: "Ver Detalles",
    price: "Precio",
    about_us: "Sobre Nosotros",
    contact_us: "Contáctenos",
    privacy: "Privacidad",
    terms: "Términos",
    language: "Idioma",
    currency: "Moneda",
    rights: "Todos los derechos reservados.",
    powered_by: "Desarrollado por Travelpayouts",
    admin_password_prompt: "Ingrese la contraseña de administrador:",
    unauthorized: "Acceso no autorizado"
  }
};

// ملف مُصلح ليعمل مع AppView (AFFILIATE_LINKS) و LandingView (PARTNERS)